export const ONTARIO_REGIONS = [
  { value: "Toronto", label: "Toronto" },
  { value: "Mississauga", label: "Mississauga" },
  { value: "Brampton", label: "Brampton" },
  { value: "Hamilton", label: "Hamilton" },
  { value: "London", label: "London" },
  { value: "Markham", label: "Markham" },
  { value: "Vaughan", label: "Vaughan" },
  { value: "Kitchener", label: "Kitchener" },
  { value: "Windsor", label: "Windsor" },
  { value: "Richmond Hill", label: "Richmond Hill" },
  { value: "Oakville", label: "Oakville" },
  { value: "Burlington", label: "Burlington" },
  { value: "Oshawa", label: "Oshawa" },
  { value: "Barrie", label: "Barrie" },
  { value: "St. Catharines", label: "St. Catharines" },
  { value: "Cambridge", label: "Cambridge" },
  { value: "Kingston", label: "Kingston" },
  { value: "Guelph", label: "Guelph" },
  { value: "Whitby", label: "Whitby" },
  { value: "Ajax", label: "Ajax" },
  { value: "Thunder Bay", label: "Thunder Bay" },
  { value: "Waterloo", label: "Waterloo" },
  { value: "Brantford", label: "Brantford" },
  { value: "Pickering", label: "Pickering" },
  { value: "Niagara Falls", label: "Niagara Falls" },
  { value: "Peterborough", label: "Peterborough" },
  { value: "Sault Ste. Marie", label: "Sault Ste. Marie" },
  { value: "Sudbury", label: "Sudbury" },
  { value: "Chatham", label: "Chatham" },
  { value: "Sarnia", label: "Sarnia" },
];

export const INDUSTRY_CATEGORIES = [
  { value: "restaurant", label: "Restaurants & Cafes" },
  { value: "real estate agent", label: "Real Estate Agents" },
  { value: "law firm", label: "Law Firms" },
  { value: "gym", label: "Gyms & Fitness Studios" },
  { value: "plumber", label: "Plumbers" },
  { value: "electrician", label: "Electricians" },
  { value: "accountant", label: "Accountants & CPAs" },
  { value: "chiropractor", label: "Chiropractors" },
  { value: "hair salon", label: "Hair Salons" },
  { value: "auto repair", label: "Auto Repair Shops" },
  { value: "mortgage broker", label: "Mortgage Brokers" },
  { value: "insurance broker", label: "Insurance Brokers" },
  { value: "marketing agency", label: "Marketing Agencies" },
  { value: "cleaning service", label: "Cleaning Services" },
  { value: "photography studio", label: "Photography Studios" },
  { value: "veterinarian", label: "Veterinarians" },
  { value: "landscaping", label: "Landscaping Companies" },
  { value: "roofing contractor", label: "Roofing Contractors" },
];
